In [2]:
import os
import polars as pl
import plotly.express as px

In [3]:
df = pl.read_excel("data/alokasi-petugas.xlsx", sheet_name = "petugas2")
df.head(10)

shape: (10, 23)
┌───────────┬─────────────┬────────────┬────────────┬───┬───────┬────────┬────────────┬────────────┐
│ nmdesa    ┆ nmsls       ┆ nama_ketua ┆ jenis      ┆ … ┆ usaha ┆ muatan ┆ pcl        ┆ pml        │
│ ---       ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---    ┆ ---        ┆ ---        │
│ str       ┆ str         ┆ str        ┆ str        ┆   ┆ i64   ┆ i64    ┆ str        ┆ str        │
╞═══════════╪═════════════╪════════════╪════════════╪═══╪═══════╪════════╪════════════╪════════════╡
│ LERMATANG ┆ RT 001 RW   ┆ LUIS       ┆ SLS        ┆ … ┆ 32    ┆ 178    ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆ BATLAYERI  ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 002 RW   ┆ RIDOLOF    ┆ SLS        ┆ … ┆ 4     ┆ 34     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆ KELBULAN   ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 003 RW   ┆ LEO        ┆ SLS        ┆ … ┆ 7     ┆ 39     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆ KELBULAN   ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 004 RW   ┆ FRITS      ┆ SLS        ┆ … ┆ 8     ┆ 55     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 002         ┆ BATLAYERI  ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 005 RW   ┆ DOMINGGUS  ┆ SLS        ┆ … ┆ 9     ┆ 45     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 002         ┆ KELBULAN   ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 006 RW   ┆ MAKLON     ┆ SLS        ┆ … ┆ 5     ┆ 46     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 003         ┆ BATMETAN   ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 007 RW   ┆ HERONIMUS  ┆ SLS        ┆ … ┆ 4     ┆ 31     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 003         ┆ WATUMLAWAR ┆            ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ HUTAN       ┆ null       ┆ NONSLS_BUK ┆ … ┆ 0     ┆ 10     ┆ Martafina  ┆ KORMASELA  │
│           ┆             ┆            ┆ AN_PERTANI ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│           ┆             ┆            ┆ AN         ┆   ┆       ┆        ┆            ┆            │
│ LERMATANG ┆ HUTAN       ┆ null       ┆ NONSLS_BUK ┆ … ┆ 0     ┆ 10     ┆ Martafina  ┆ KORMASELA  │
│           ┆             ┆            ┆ AN_PERTANI ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│           ┆             ┆            ┆ AN         ┆   ┆       ┆        ┆            ┆            │
│ LATDALAM  ┆ RT 001 RW   ┆ NITANEL    ┆ SLS        ┆ … ┆ 11    ┆ 40     ┆ Stovia     ┆ KORMASELA  │
│           ┆ 001         ┆ BATLAYERI  ┆            ┆   ┆       ┆        ┆ sanamas    ┆ KANIKIR    │
│           ┆             ┆            ┆            ┆   ┆       ┆        ┆ Lerebulan  ┆            │
└───────────┴─────────────┴────────────┴────────────┴───┴───────┴────────┴────────────┴────────────┘

In [4]:
df.columns

['nmdesa',
 'nmsls',
 'nama_ketua',
 'jenis',
 'kdprov',
 'kdkab',
 'kdkec',
 'kddesa',
 'kdsls',
 'kdsubsls',
 'klas',
 'nmprov',
 'nmkab',
 'nmkec',
 'kk',
 'btt',
 'bttk',
 'bku',
 'bbtt_nonusaha',
 'usaha',
 'muatan',
 'pcl',
 'pml']

In [ ]:
selected_columns = [
  'nmdesa',
 'nmsls',
 'jenis',
 'nmkec',
 'kk',
 'usaha',
 'muatan',
 'pcl',
 'pml']

selected_columns

['nmdesa', 'nmsls', 'jenis', 'nmkec', 'kk', 'usaha', 'muatan', 'pcl', 'pml']

In [6]:
df2 = df.select(pl.col(selected_columns))
df2.head(10)

shape: (10, 9)
┌───────────┬─────────────┬────────────┬────────────┬───┬───────┬────────┬────────────┬────────────┐
│ nmdesa    ┆ nmsls       ┆ jenis      ┆ nmkec      ┆ … ┆ usaha ┆ muatan ┆ pcl        ┆ pml        │
│ ---       ┆ ---         ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---    ┆ ---        ┆ ---        │
│ str       ┆ str         ┆ str        ┆ str        ┆   ┆ i64   ┆ i64    ┆ str        ┆ str        │
╞═══════════╪═════════════╪════════════╪════════════╪═══╪═══════╪════════╪════════════╪════════════╡
│ LERMATANG ┆ RT 001 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 32    ┆ 178    ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 002 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 4     ┆ 34     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 003 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 7     ┆ 39     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 001         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 004 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 8     ┆ 55     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 002         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 005 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 9     ┆ 45     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 002         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 006 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 5     ┆ 46     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 003         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ RT 007 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 4     ┆ 31     ┆ Martafina  ┆ KORMASELA  │
│           ┆ 003         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│ LERMATANG ┆ HUTAN       ┆ NONSLS_BUK ┆ TANIMBAR   ┆ … ┆ 0     ┆ 10     ┆ Martafina  ┆ KORMASELA  │
│           ┆             ┆ AN_PERTANI ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│           ┆             ┆ AN         ┆            ┆   ┆       ┆        ┆            ┆            │
│ LERMATANG ┆ HUTAN       ┆ NONSLS_BUK ┆ TANIMBAR   ┆ … ┆ 0     ┆ 10     ┆ Martafina  ┆ KORMASELA  │
│           ┆             ┆ AN_PERTANI ┆ SELATAN    ┆   ┆       ┆        ┆ Lamere     ┆ KANIKIR    │
│           ┆             ┆ AN         ┆            ┆   ┆       ┆        ┆            ┆            │
│ LATDALAM  ┆ RT 001 RW   ┆ SLS        ┆ TANIMBAR   ┆ … ┆ 11    ┆ 40     ┆ Stovia     ┆ KORMASELA  │
│           ┆ 001         ┆            ┆ SELATAN    ┆   ┆       ┆        ┆ sanamas    ┆ KANIKIR    │
│           ┆             ┆            ┆            ┆   ┆       ┆        ┆ Lerebulan  ┆            │
└───────────┴─────────────┴────────────┴────────────┴───┴───────┴────────┴────────────┴────────────┘

In [11]:
df2 = (
  df2.with_columns(
  nmdesa = pl.col("nmdesa").str.to_titlecase(),
  nmkec = pl.col('nmkec').str.to_titlecase(),
  pcl = pl.col('pcl').str.to_titlecase(),
  pml = pl.col('pml').str.to_titlecase()
)
.select(
  pl.col(['nmkec', 'nmdesa', 'nmsls', 'jenis', 'pml', 'pcl', 'kk', 'usaha', 'muatan'])
)
)
df2.head(5)

shape: (5, 9)
┌──────────┬───────────┬───────────────┬───────┬───┬──────────────────┬─────┬───────┬────────┐
│ nmkec    ┆ nmdesa    ┆ nmsls         ┆ jenis ┆ … ┆ pcl              ┆ kk  ┆ usaha ┆ muatan │
│ ---      ┆ ---       ┆ ---           ┆ ---   ┆   ┆ ---              ┆ --- ┆ ---   ┆ ---    │
│ str      ┆ str       ┆ str           ┆ str   ┆   ┆ str              ┆ i64 ┆ i64   ┆ i64    │
╞══════════╪═══════════╪═══════════════╪═══════╪═══╪══════════════════╪═════╪═══════╪════════╡
│ Tanimbar ┆ Lermatang ┆ RT 001 RW 001 ┆ SLS   ┆ … ┆ Martafina Lamere ┆ 139 ┆ 32    ┆ 178    │
│ Selatan  ┆           ┆               ┆       ┆   ┆                  ┆     ┆       ┆        │
│ Tanimbar ┆ Lermatang ┆ RT 002 RW 001 ┆ SLS   ┆ … ┆ Martafina Lamere ┆ 28  ┆ 4     ┆ 34     │
│ Selatan  ┆           ┆               ┆       ┆   ┆                  ┆     ┆       ┆        │
│ Tanimbar ┆ Lermatang ┆ RT 003 RW 001 ┆ SLS   ┆ … ┆ Martafina Lamere ┆ 32  ┆ 7     ┆ 39     │
│ Selatan  ┆           ┆               ┆       ┆   ┆                  ┆     ┆       ┆        │
│ Tanimbar ┆ Lermatang ┆ RT 004 RW 002 ┆ SLS   ┆ … ┆ Martafina Lamere ┆ 46  ┆ 8     ┆ 55     │
│ Selatan  ┆           ┆               ┆       ┆   ┆                  ┆     ┆       ┆        │
│ Tanimbar ┆ Lermatang ┆ RT 005 RW 002 ┆ SLS   ┆ … ┆ Martafina Lamere ┆ 35  ┆ 9     ┆ 45     │
│ Selatan  ┆           ┆               ┆       ┆   ┆                  ┆     ┆       ┆        │
└──────────┴───────────┴───────────────┴───────┴───┴──────────────────┴─────┴───────┴────────┘

In [8]:
df2.write_excel('data/alokasi-petugas-cleaned.xlsx')

In [12]:
df2 = (
  df2.with_columns(
    (pl.col("muatan")*0.4).ceil().alias("muatan_40"),
    (pl.col("usaha")*0.4).ceil().alias("usaha_40"),
    (pl.col("usaha")*0.6).ceil().alias("usaha_60"),
    (pl.col("muatan")*0.6).ceil().alias("muatan_60")
  )
  .with_columns(
    (pl.col("muatan_60")/30).ceil().alias("target_harian_ruta_termin1"),
    (pl.col("usaha_40")/30).ceil().alias("target_harian_usaha_termin1"),
    (pl.col("muatan_60")/45).ceil().alias("target_harian_ruta_termin2"),
    (pl.col("usaha_60")/45).ceil().alias("target_harian_usaha_termin2")
  )
  
)

df2.head(10)

shape: (10, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ nmkec     ┆ nmdesa    ┆ nmsls     ┆ jenis     ┆ … ┆ target_ha ┆ target_ha ┆ target_ha ┆ target_h │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ rian_ruta ┆ rian_usah ┆ rian_ruta ┆ arian_us │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ _termin1  ┆ a_termin1 ┆ _termin2  ┆ aha_term │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ in2      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Tanimbar  ┆ Lermatang ┆ RT 001 RW ┆ SLS       ┆ … ┆ 4.0       ┆ 1.0       ┆ 3.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 001       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 002 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 001       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 003 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 001       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 004 RW ┆ SLS       ┆ … ┆ 2.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 002       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 005 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 002       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 006 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ RT 007 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ HUTAN     ┆ NONSLS_BU ┆ … ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0      │
│ Selatan   ┆           ┆           ┆ KAN_PERTA ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NIAN      ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Lermatang ┆ HUTAN     ┆ NONSLS_BU ┆ … ┆ 1.0       ┆ 0.0       ┆ 1.0       ┆ 0.0      │
│ Selatan   ┆           ┆           ┆ KAN_PERTA ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ NIAN      ┆   ┆           ┆           ┆           ┆          │
│ Tanimbar  ┆ Latdalam  ┆ RT 001 RW ┆ SLS       ┆ … ┆ 1.0       ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│ Selatan   ┆           ┆ 001       ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
df2.columns

['nmkec',
 'nmdesa',
 'nmsls',
 'jenis',
 'pml',
 'pcl',
 'kk',
 'usaha',
 'muatan',
 'muatan_40',
 'usaha_40',
 'usaha_60',
 'muatan_60',
 'target_harian_ruta_termin1',
 'target_harian_usaha_termin1',
 'target_harian_ruta_termin2',
 'target_harian_usaha_termin2']

In [22]:
df2 = (
  df2.select(
    pl.col('pml', 'pcl', 'target_harian_ruta_termin1', 'target_harian_usaha_termin1', 'target_harian_ruta_termin2', 'target_harian_usaha_termin2')
  )
)

df2.head(10)

shape: (10, 6)
┌───────────┬─────────────────┬─────────────────┬────────────────┬────────────────┬────────────────┐
│ pml       ┆ pcl             ┆ target_harian_r ┆ target_harian_ ┆ target_harian_ ┆ target_harian_ │
│ ---       ┆ ---             ┆ uta_termin1     ┆ usaha_termin1  ┆ ruta_termin2   ┆ usaha_termin2  │
│ str       ┆ str             ┆ ---             ┆ ---            ┆ ---            ┆ ---            │
│           ┆                 ┆ f64             ┆ f64            ┆ f64            ┆ f64            │
╞═══════════╪═════════════════╪═════════════════╪════════════════╪════════════════╪════════════════╡
│ Kormasela ┆ Martafina       ┆ 4.0             ┆ 1.0            ┆ 3.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 2.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 0.0            ┆ 1.0            ┆ 0.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Martafina       ┆ 1.0             ┆ 0.0            ┆ 1.0            ┆ 0.0            │
│ Kanikir   ┆ Lamere          ┆                 ┆                ┆                ┆                │
│ Kormasela ┆ Stovia Sanamas  ┆ 1.0             ┆ 1.0            ┆ 1.0            ┆ 1.0            │
│ Kanikir   ┆ Lerebulan       ┆                 ┆                ┆                ┆                │
└───────────┴─────────────────┴─────────────────┴────────────────┴────────────────┴────────────────┘

In [18]:
target_ppl = (
  df2
  .select(pl.col('pcl', 'target_harian_ruta_termin1', 'target_harian_ruta_termin2', 'target_harian_usaha_termin1', 'target_harian_usaha_termin2'))
  .group_by(pl.col("pcl"))
  .sum()
)

target_ppl

shape: (112, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ pcl               ┆ target_harian_rut ┆ target_harian_rut ┆ target_harian_usa ┆ target_harian_us │
│ ---               ┆ a_termin1         ┆ a_termin2         ┆ ha_termin1        ┆ aha_termin2      │
│ str               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│                   ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ Anni Silalebit    ┆ 8.0               ┆ 6.0               ┆ 4.0               ┆ 4.0              │
│ Martafina Lamere  ┆ 13.0              ┆ 11.0              ┆ 7.0               ┆ 7.0              │
│ Ronaldo Sanabuky  ┆ 11.0              ┆ 9.0               ┆ 8.0               ┆ 8.0              │
│ Abraham Petrus    ┆ 10.0              ┆ 8.0               ┆ 4.0               ┆ 4.0              │
│ Prawira Kelbula…  ┆                   ┆                   ┆                   ┆                  │
│ Fitria Handayani  ┆ 10.0              ┆ 6.0               ┆ 4.0               ┆ 4.0              │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ Supriadi Unmehopa ┆ 9.0               ┆ 6.0               ┆ 5.0               ┆ 5.0              │
│ Moses Tawun       ┆ 8.0               ┆ 4.0               ┆ 4.0               ┆ 4.0              │
│ Josep Erwin       ┆ 9.0               ┆ 6.0               ┆ 3.0               ┆ 3.0              │
│ Matkusa           ┆                   ┆                   ┆                   ┆                  │
│ Abner Lerebulan   ┆ 9.0               ┆ 6.0               ┆ 3.0               ┆ 3.0              │
│ Thitin Iryani     ┆ 8.0               ┆ 6.0               ┆ 4.0               ┆ 4.0              │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [20]:
target_pml = (
  df2
  .select(pl.col('pml', 'target_harian_ruta_termin1', 'target_harian_ruta_termin2', 'target_harian_usaha_termin1', 'target_harian_usaha_termin2'))
  .group_by(pl.col("pml"))
  .sum()
)

target_pml

shape: (16, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ pml               ┆ target_harian_rut ┆ target_harian_rut ┆ target_harian_usa ┆ target_harian_us │
│ ---               ┆ a_termin1         ┆ a_termin2         ┆ ha_termin1        ┆ aha_termin2      │
│ str               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│                   ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ Kormasela Kanikir ┆ 97.0              ┆ 73.0              ┆ 48.0              ┆ 48.0             │
│ Yuchie T. Simar   ┆ 52.0              ┆ 45.0              ┆ 31.0              ┆ 31.0             │
│ Demny             ┆                   ┆                   ┆                   ┆                  │
│ Semuel S. S.      ┆ 73.0              ┆ 57.0              ┆ 41.0              ┆ 41.0             │
│ Jawar             ┆                   ┆                   ┆                   ┆                  │
│ Mita Nuniary      ┆ 77.0              ┆ 54.0              ┆ 49.0              ┆ 49.0             │
│ Paulinus          ┆ 70.0              ┆ 50.0              ┆ 34.0              ┆ 34.0             │
│ Angwarmasse       ┆                   ┆                   ┆                   ┆                  │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ Mutiara Dewanti   ┆ 93.0              ┆ 68.0              ┆ 36.0              ┆ 36.0             │
│ Clementina Ora…   ┆                   ┆                   ┆                   ┆                  │
│ Simon Warditty    ┆ 68.0              ┆ 52.0              ┆ 29.0              ┆ 29.0             │
│ Maikel Simon      ┆ 63.0              ┆ 49.0              ┆ 43.0              ┆ 43.0             │
│ Mahoklory         ┆                   ┆                   ┆                   ┆                  │
│ Mintje Angwarmase ┆ 62.0              ┆ 47.0              ┆ 35.0              ┆ 35.0             │
│ Laitjaman Luis    ┆ 47.0              ┆ 32.0              ┆ 23.0              ┆ 23.0             │
│ Rumahengga        ┆                   ┆                   ┆                   ┆                  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘